version: '3.9'

networks:
  local-network: {}

volumes:
  local-postgres-data: {}

x-base-image: &base-image
  restart: always
  networks:
    local-network: {}
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  local-postgres:
    <<: *base-image
    image: "postgres:14.1-alpine"
    hostname: local-postgres
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'db-name'
      POSTGRES_USER: 'db-user'
      POSTGRES_PASSWORD: 'db-pass'

  local-backup-postgresql:
    <<: *base-image
    image: local-backup-postgresql
    hostname: local-backup-postgresql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: 'testapp'
      CRON_EXPRESSION: '* * * * *'
      AWS_ACCESS_KEY_ID: 'set-me'
      AWS_SECRET_ACCESS_KEY: 'set-me'
      AWS_BUCKET_NAME: 'set-me'
      SLACK_API_TOKEN: 'set-me'
      SLACK_CHANNEL: '#infra-backup'
      POSTGRES_HOST: 'local-postgres'
      POSTGRES_DB: 'db-name'
      POSTGRES_USER: 'db-user'
      POSTGRES_PASSWORD: 'db-pass'
