version: "3.9"

networks:
  local-network: {}

volumes:
  local-postgres-data: {}

x-base-image: &base-image
  restart: always
  networks:
    local-network: {}
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  local-autobackup:
    <<: *base-image
    image: local-autobackup
    hostname: local-autobackup
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - PYTHON_VERSION=3.10
    platform: linux/amd64
    environment:
      BACKUP_APP_NAME: "infra"
      BACKUP_CRON_EXPRESSION: "* * * * *"
      BACKUP_USE_CONFIG: "on"
      BACKUP_CONFIG: |
        primary-db:
          target:
            type: postgresql
            params:
              postgres_host: ""
              postgres_port: ""
              postgres_db: ""
              postgres_user: ""
              postgres_password: ""
          storages:
          - type: remote
            params:
              ssh_username: ""
              ssh_password: ""
              ssh_host: ""
              ssh_port: ""
              remote_dir_path: ""
          notifiers:
          - type: telegram
            params:
              chat_ids:
              - []
              bot_token: ""
