version: "3.9"

networks:
  local-network: {}

volumes:
  local-postgres-data: {}

x-base-image: &base-image
  restart: always
  networks:
    local-network: {}
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  local-postgres:
    <<: *base-image
    image: "postgres:14.1-alpine"
    hostname: local-postgres
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db-name"
      POSTGRES_USER: "db-user"
      POSTGRES_PASSWORD: "db-pass"

  local-backup:
    <<: *base-image
    image: local-backup
    hostname: local-backup
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/backup/data
    environment:
      BACKUP_APP_NAME: "nss"
      BACKUP_CRON_EXPRESSION: "* * * * *"
      BACKUP_USE_CONFIG: "on"
      BACKUP_CONFIG: |
        primary-db:
          target:
            type: postgresql
            params:
              postgres_host: "local-postgres"
              postgres_port: "5432"
              postgres_db: "db-name"
              postgres_user: "db-user"
              postgres_password: "db-pass"
          storages: []
          notifiers: []
